[book]
authors = ["Zaid Mukaddam"]
language = "en"
multilingual = false
src = "src"
title = "The Warp Guide"

[build]
build-dir = "../_site/guide"

[output.html]
site-url = "/guide/"
no-section-label = true
copy-fonts = false
curly-quotes = true
additional-js = ["scripts/language-warp.js"]
additional-css = ["styles/custom.css"]
